version: "3.8"
services:
  smilecdr:
    container_name: smilecdr_local
    image: smilecdr_local
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9100:9100"
      - "8001:8001"
      - "9200:9200"
      - "9201:9201"
    environment:
      - DB_URL_MGR=${DB_URL_MGR}
      - DB_URL_FHIR=${DB_URL_FHIR}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    volumes:
      - db:/home/smile/smilecdr/database
      - log:/home/smile/smilecdr/log
      - mq:/home/smile/smilecdr/activemq-data
    restart: "unless-stopped"
volumes:
  db:
  log:
  mq: